name: 'Hello World!'
description: 'Great someone and record the time'
inputs:
  who-to-greet: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

outputs: 
  time: # id of input
    description: 'the time we greated you'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.who-to-greet }}
